### ISSUE TITLE
Sharing a single (factory) ViewModel between ViewWidgets causes a re-initialized final error.

### ISSUE THREAD

**Issue by LozCool** [buttonsrtoys/mvvm_plus#45] opened 2023-11-02 17:09 UTC
If you want to share a (single instance) ViewModel between ViewWidgets in MVVM+, it would be usual to use a higher level Bilocater that lives in the registry. Something like this:

```
class MainPage extends StatelessWidget
{
  @override
  Widget build(
      BuildContext context)
  {
    return Scaffold(
        body: Bilocator<ContainerViewModel>(
            builder: ()
            {
              return ContainerViewModel();
            },
            location: Location.registry,
            name: 'ContainerViewModel',
            child: SafeArea(
                child: PageContainer()
            )
        )
}
```

And then use it in each ViewWidget like this:

```
class PageContainer extends ViewWidget<ContainerViewModel> {
  PageContainer({super.key}) :
        super(builder: () => Bilocator.get(name: 'ContainerViewModel'));

  .. .. ..
}
```

or, for the second ViewWidget that needs the same ViewModel:

```
class PageHeader extends ViewWidget<ContainerViewModel> {
  PageHeader({super.key}) :
        super(builder: () => Bilocator.get(name: 'ContainerViewModel'));

  .. .. ..
}

```
When the second ViewWidget (PageHeader above) is created, MVVM+ raises an exception. Something like:

    ‘LateInitializationError: Field '_context@42364977' has already been initialized’

This, I think, is because the ViewModel builder is internally re-initializing already initialized (late final) members.

**Comment by buttonsrtoys** [comment] 2023-11-02 21:51
Ah. Interesting use case, Loz. I didn't quite follow what you were doing via email but see what's going on now.

The issue is that, under the hood, ViewModels are given the context of the Widget that built it. That way, the ViewModel can use the context to "get" and "listen" to other ViewModels and Properties. What's happening in your example is that a Widget built a ViewModel and then gave it its context. Then, when the `builder` of the second Widgets retrieved the same ViewModel, it also trying to assign it its context, but it was already assigned and is a `late final` which is why you got the exception.

ViewModels in the widget tree need to know where they are in the tree, so I don't anticipate changing this approach anytime soon. But it sounds like there is an alternative, maybe better way to do what you want.

My recommendation for your second widgets to subclass from `StatelessViewWidget` instead of `ViewWidget`. StatelessViewWidget has no ViewModel (so no builder) and instead "gets" or "listens" too one or more ViewModels owned by other widgets. Check out the mvvm+ examples. Most of the widgets in it are StatelessViewModels.

E.g., here's an class in the mvvm+ example that subclasses StatelessViewWidget. You can see in the class how it uses `get` and `listenTo` to access the other ViewClass.

```
/// Demonstrates [get] and [listenTo] for a [Model]
class ModelWidget extends StatelessViewWidget {
  ModelWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Text('get/listenTo Model'),
        Text('${listenTo<CounterModel>().count}'),
        const SizedBox(height: 10),
        Fab(onPressed: get<CounterModel>().incrementCount),
      ],
    );
  }
}
```

When you and I chatted via email, I thought you were trying to access a ViewModel in the registry from within the body of the constructor, like this

```
class MyWidget extends ViewWidget<MyWidgetViewModel> {
  MyWidget({super.key}) : super(builder: () => MyWidgetViewModel()) {
     final value = get<Counter>(); // <-- This should work if "Counter" is in the registry, but was causing an exception, so a bug
  }

  @override
  Widget build(BuildContext context) {
    return Text(viewModel.someText); 
  }
}
```

which is a use case that I did not anticipate and was indeed a bug. So, I just pushed version 1.5.4 that fixes this, though you may not need it.

I hope that clears things up. Please let me know either way.

**Comment by LozCool** [comment] 2023-11-03 14:03
Hi Rich,

 

Based on your comments I think I have finally got a working solution. By the way, the description that you gave about late final was kind of what I thought was happening, so thanks for the Super Quick fix.

 

Here is what I did. First, I no longer use Bilocator directly to plant a ContainerViewModel in the tree within the Scaffold code.

 

Second, I create a ContainerViewModel in the PageContainer ViewWidget instance like this:

 

class PageContainer extends ViewWidget<ContainerViewModel> {
  PageContainer({super.key})
      : super(
      builder: () {
        return ContainerViewModel();
      },
      location: Location.registry
  );

  ...
}

 

Finally, the other classes are now StatelessViewWidgets, for example:

 

class PageContent extends StatelessViewWidget {
  PageContent({super.key});

  @override
  Widget build(BuildContext context) {
    final ContainerViewModel viewModel = get<ContainerViewModel>();

    ...
  }
}

 

I do the above for PageHeader, PageSideBar and PageContent and they all find the (single) ContainerViewModel instance from the registry.

 

The critical part above is the ‘location: Location.registry’ line in PageContainer. Without this, the other classes can’t find the ViewModel.

 

According to this page:

 

                ***@***.***/flutter-state-management-with-mvvm-1b55e6911975

 

in the ‘Retrieving ViewModels from anywhere’ section, this should be accomplished by ‘register: true’. But that is not possible anymore, so I think the documentation may need to be updated?

 

Anyway, thanks so much for your help and such a quick turn-around.

 

Best regards, Loz.

**Comment by buttonsrtoys** [comment] 2023-11-03 15:14
Hi Loz,

That's great you got it working! I understood your email except the very
end where you said, "But that is not possible anymore." What is not
possible? Retrieving a ViewModel from the tree? That should be working.

If you don't set `location: Location.registry` then mvvm+ put the ViewModel
on the widget tree. Other widgets should be able to then retrieve the
ViewModel by using the get function and setting its "context" parameter. So,

   final viewModel = get<ContainerViewModel>(context: context);

The get function then looks for the CountainerViewModel in an ancestor
widget. It won't work if the ViewModel isn't owned by an ancestor (e.g.,
it's a child or on another widget tree branch.)

Is that what you mean or were you referring to something else?

Rich

**Comment by LozCool** [comment] 2023-11-03 15:58
Hi again Rich,

 

Well, I didn’t quite mean that. The documentation from that page gives an example (under the ‘Retrieving ViewModels from anywhere’ section):

 

class MyOtherWidget extends View<MyOtherWidgetViewModel> {
    MyOtherWidget(super.key) : super(
       viewModelBuilder: () => MyOtherWidgetViewModel(
         // Register ViewModel:
         register: true, 
       ),
    );
}

 

That doesn’t compile anymore. But it’s on medium.com and probably written by you a long time ago (Aug 10, 2022).

 

This has solved everything for me when you said below:

 

                final viewModel = get<ContainerViewModel>(context: context);

 

I hadn’t included the context argument so was forced get the ViewModel from the registry (having put it there using ‘location: Location.registry’).

 

Once again, many thanks. And happy days, Loz.

**Comment by buttonsrtoys** [comment] 2023-11-03 16:06
Ah. Yes. That's from and outdated version and needs to be updated. Thanks!

**Comment by LozCool** [comment] 2023-11-03 16:18
FYI, Rich:

 

class PageContainer extends ViewWidget<ContainerViewModel> {
  PageContainer({super.key})
      : super(
      builder: () {
        return ContainerViewModel();
      },
//      location: Location.tree
  );

 

and this:

 

class PageContent extends StatelessViewWidget
{
  PageContent({super.key});

  @override
  Widget build(BuildContext context) {
    final ContainerViewModel viewModel = get<ContainerViewModel>(context: context);

 

Doesn’t work. You get a runtime error.

 

The location must be specified specifically as ‘tree’, not what you said earlier (ie, its not the default, which is registry). (If I uncomment the location: Location.tree line it runs fine).

 

Anyway, have a great day and thanks.

 

Loz.

**Closed as completed** 2023-11-03 19:05 UTC
